from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from app.core.security import get_current_user, require_investigator, CurrentUser
from app.core.supabase_client import get_supabase_admin
from app.models.schemas import (
    CaseCreate, CaseUpdate, CaseResponse, CaseListResponse, MessageResponse
)
from app.services.audit_log import write_officer_audit
import logging

router = APIRouter(prefix="/cases", tags=["Cases"])
logger = logging.getLogger(__name__)


@router.get("", response_model=CaseListResponse)
async def list_cases(
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    status: Optional[str] = Query(None),
    priority: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    current_user: CurrentUser = Depends(get_current_user),
):
    """List cases accessible to the current user."""
    try:
        db = get_supabase_admin()
        query = db.table("cases").select("*, assignee:assigned_to(id, full_name, email, role)")

        # Removed role filters to allow full collaboration

        if status:
            query = query.eq("status", status)
        if priority:
            query = query.eq("priority", priority)

        # Pagination
        offset = (page - 1) * page_size
        result = query.order("created_at", desc=True).range(offset, offset + page_size - 1).execute()

        # Count total
        count_result = db.table("cases").select("id", count="exact").execute()
        total = count_result.count or 0

        return CaseListResponse(
            items=result.data or [],
            total=total,
            page=page,
            page_size=page_size,
        )
    except Exception as e:
        logger.error(f"Error listing cases: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("", response_model=CaseResponse, status_code=status.HTTP_201_CREATED)
async def create_case(
    case_data: CaseCreate,
    current_user: CurrentUser = Depends(require_investigator),
):
    """Create a new investigation case."""
    try:
        db = get_supabase_admin()
        payload = case_data.model_dump(exclude_none=True)
        payload["created_by"] = current_user.id
        payload["case_number"] = ""  # Will be auto-generated by trigger

        try:
            result = db.table("cases").insert(payload).execute()
        except Exception as insert_err:
            logger.warning("Case insert with ops fields failed, retrying core columns: %s", insert_err)
            for key in ("fir_number", "police_station", "ncrp_complaint_id", "complainant_name", "sections_of_law", "funds_frozen_inr"):
                payload.pop(key, None)
            result = db.table("cases").insert(payload).execute()
        if not result.data:
            raise HTTPException(status_code=500, detail="Failed to create case")

        created = result.data[0]
        write_officer_audit(
            db,
            action="CREATE_FIR",
            target=created.get("fir_number") or created.get("case_number") or created.get("title"),
            officer_id=current_user.id,
            officer_email=current_user.email,
            status="logged",
        )
        return created
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error creating case: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{case_id}", response_model=CaseResponse)
async def get_case(
    case_id: str,
    current_user: CurrentUser = Depends(get_current_user),
):
    """Get a specific case by ID."""
    try:
        db = get_supabase_admin()
        result = db.table("cases").select(
            "*, assignee:assigned_to(id, full_name, email, role)"
        ).eq("id", case_id).single().execute()

        if not result.data:
            raise HTTPException(status_code=404, detail="Case not found")

        case = result.data
        # Removed access check to allow full collaboration


        return case
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching case {case_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/{case_id}", response_model=CaseResponse)
async def update_case(
    case_id: str,
    update_data: CaseUpdate,
    current_user: CurrentUser = Depends(require_investigator),
):
    """Update a case."""
    try:
        db = get_supabase_admin()
        # Verify access
        existing = db.table("cases").select("created_by, assigned_to").eq("id", case_id).single().execute()
        if not existing.data:
            raise HTTPException(status_code=404, detail="Case not found")

        case = existing.data
        # Removed access check to allow full collaboration


        payload = update_data.model_dump(exclude_none=True)
        result = db.table("cases").update(payload).eq("id", case_id).execute()

        if not result.data:
            raise HTTPException(status_code=500, detail="Update failed")
        return result.data[0]
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating case {case_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/{case_id}", response_model=MessageResponse)
async def delete_case(
    case_id: str,
    current_user: CurrentUser = Depends(require_investigator),
):
    """Delete a case (admin only)."""
    # Removed admin check for deletion to allow full collaboration


    try:
        db = get_supabase_admin()
        result = db.table("cases").delete().eq("id", case_id).execute()
        return MessageResponse(message=f"Case {case_id} deleted successfully")
    except Exception as e:
        logger.error(f"Error deleting case {case_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{case_id}/stats")
async def get_case_stats(
    case_id: str,
    current_user: CurrentUser = Depends(get_current_user),
):
    """Get aggregated statistics for a case."""
    try:
        db = get_supabase_admin()
        evidence_count = db.table("evidence").select("id", count="exact").eq("case_id", case_id).execute()
        findings_count = db.table("findings").select("id", count="exact").eq("case_id", case_id).execute()
        timeline_count = db.table("timeline_events").select("id", count="exact").eq("case_id", case_id).execute()

        critical_findings = db.table("findings").select("id", count="exact").eq("case_id", case_id).eq("severity", "critical").execute()

        return {
            "evidence_count": evidence_count.count or 0,
            "findings_count": findings_count.count or 0,
            "timeline_events": timeline_count.count or 0,
            "critical_findings": critical_findings.count or 0,
        }
    except Exception as e:
        logger.error(f"Error fetching case stats: {e}")
        raise HTTPException(status_code=500, detail=str(e))
